# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0007_auto_20170818_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='availability',
            field=models.ManyToManyField(to='tutorprofile.Availability'),
        ),
    ]
