# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0008_tutorprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
