# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0012_tutorprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='email',
            field=models.EmailField(default='contact@mytutormarin.org', max_length=254),
            preserve_default=False,
        ),
    ]
