# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0013_tutorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='phone',
            field=models.CharField(default='#', max_length=20),
            preserve_default=False,
        ),
    ]
